# Generated by Django 3.1.6 on 2021-02-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201218_1626'),
        ('api', '0002_auto_20210216_2101'),
    ]

    operations = [
    ]
