# Generated by Django 3.1.6 on 2021-02-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('api', '0003_merge_20210222_0052'),
    ]

    operations = [
    ]
